default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tool_box_development

test:
  <<: *default
  database: tool_box_test

production:
  <<: *default
  database: tool_box_production
  username: tool_box
  password: <%= ENV['TOOL_BOX_DATABASE_PASSWORD']
